{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 info pnpm": {
    "err": {
      "name": "Error",
      "message": "Command failed with ENOENT: @protobuf-ts/runtime\nspawn @protobuf-ts/runtime ENOENT",
      "code": "ENOENT",
      "stack": "Error: Command failed with ENOENT: @protobuf-ts/runtime\nspawn @protobuf-ts/runtime ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)\n    at onErrorNT (node:internal/child_process:475:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    }
  },
  "2 error pnpm": {
    "errno": -2,
    "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
    "syscall": "spawn @protobuf-ts/runtime",
    "path": "@protobuf-ts/runtime",
    "spawnargs": [],
    "originalMessage": "spawn @protobuf-ts/runtime ENOENT",
    "shortMessage": "Command failed with ENOENT: @protobuf-ts/runtime\nspawn @protobuf-ts/runtime ENOENT",
    "command": "@protobuf-ts/runtime",
    "escapedCommand": "\"@protobuf-ts/runtime\"",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false,
    "prefix": "/home/sam/projects/syncapod/web",
    "err": {
      "name": "pnpm",
      "message": "Command failed with ENOENT: @protobuf-ts/runtime\nspawn @protobuf-ts/runtime ENOENT",
      "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
      "stack": "Error: Command failed with ENOENT: @protobuf-ts/runtime\nspawn @protobuf-ts/runtime ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)\n    at onErrorNT (node:internal/child_process:475:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    }
  }
}